name: destiny_clan
version: 0.0.1
description: Manage the roster of a Bungie clan.
dependencies:
  args: ^0.13.4
  bungie_client:
    git:
      url: https://github.com/pylaligand/dart-bungie-client.git
      ref: master
