name: destiny-common
version: 0.0.1
description: Common utilities for Destiny-related scripts.
dependencies:
  args: any
  collection: any
  googleapis: any
  googleapis_auth: any
  http: any
  test: any
